// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzSVrcCm8RGbXBjlaN4YYyzbQAcAThWKI',
    appId: '1:544124172877:web:e01981f64733836872fa04',
    messagingSenderId: '544124172877',
    projectId: 'workforce-65127',
    authDomain: 'workforce-65127.firebaseapp.com',
    storageBucket: 'workforce-65127.firebasestorage.app',
    measurementId: 'G-T5RDJ2QP41',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCss5zSPVf4hKNSvkznEI_HkAZidnbCsrE',
    appId: '1:544124172877:android:a7dc6907b757d7d172fa04',
    messagingSenderId: '544124172877',
    projectId: 'workforce-65127',
    storageBucket: 'workforce-65127.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6f97GMyBd54XX7AqzN3Btec2qCt46z3w',
    appId: '1:544124172877:ios:13d5fc300b5d303c72fa04',
    messagingSenderId: '544124172877',
    projectId: 'workforce-65127',
    storageBucket: 'workforce-65127.firebasestorage.app',
    iosBundleId: 'com.dmn.auftragnowclient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6f97GMyBd54XX7AqzN3Btec2qCt46z3w',
    appId: '1:544124172877:ios:13d5fc300b5d303c72fa04',
    messagingSenderId: '544124172877',
    projectId: 'workforce-65127',
    storageBucket: 'workforce-65127.firebasestorage.app',
    iosBundleId: 'com.dmn.auftragnowclient',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzSVrcCm8RGbXBjlaN4YYyzbQAcAThWKI',
    appId: '1:544124172877:web:12c1c15076d6fbca72fa04',
    messagingSenderId: '544124172877',
    projectId: 'workforce-65127',
    authDomain: 'workforce-65127.firebaseapp.com',
    storageBucket: 'workforce-65127.firebasestorage.app',
    measurementId: 'G-EGKFCM58WH',
  );
}
